name: Deploy FE (stage)

on:
  push:
    branches: [stage]

jobs:
  build:
    runs-on: stage.othaimglobal.dnetdemo.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node + pnpm
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install pnpm
        run: npm install -g pnpm@10.30.3

      - name: Deploy source to server path
        run: |
          sudo cp -r * /www/wwwroot/stage.othaimglobal.dnetdemo.com/web/

      - name: Install dependencies
        working-directory: /www/wwwroot/stage.othaimglobal.dnetdemo.com/web/
        run: |
          sudo pnpm install --frozen-lockfile --force

      - name: Build Next.js app
        working-directory: /www/wwwroot/stage.othaimglobal.dnetdemo.com/web/
        run: sudo pnpm build

      - name: restart pm2 service
        run: cd /www/wwwroot/stage.othaimglobal.dnetdemo.com/web/ && sudo pm2 reload othaimglobal-frontend-stage --update-env
